const MARKET = 'MARKET'
const BEST_BID = 'BEST_BID'
const BEST_ASK = 'BEST_ASK'

module.exports = {
  MARKET,
  BEST_BID,
  BEST_ASK,
  ORDER_TYPES: [MARKET, BEST_BID, BEST_ASK],
  ORDER_TYPES_TO_BFX: {
    [MARKET]: 'EXCHANGE MARKET',
    [BEST_BID]: 'EXCHANGE LIMIT',
    [BEST_ASK]: 'EXCHANGE LIMIT'
  },
  ORDER_TYPES_TO_MARGIN_BFX: {
    [MARKET]: 'MARKET',
    [BEST_BID]: 'LIMIT',
    [BEST_ASK]: 'LIMIT'
  }
}
